from typing import Annotated

from langchain_core.documents import Document
from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from pydantic import BaseModel, Field

from rag_app.retrieval.schema import LLMAnswer

MessagesState = Annotated[list[AnyMessage],add_messages]

class InputRetrievalState(BaseModel):
    messages: Annotated[
        MessagesState,
        Field(
            description="User Question for Retrieval"
        )
    ]
    
class OutputRetrievalState(BaseModel):
    messages: Annotated[
        MessagesState,
        Field(
            description="Generation AI Message"
        )
    ]
    llm_questions: Annotated[
        list[str],
        Field(
            default_factory=list,
            description=(
                "List of alternative search queries generated by the generate_questions node. These variants are sent to "
                "the vector store to broaden recall while staying semantically close to the original question."
            ),
        ),
    ]
    retrieved_docs: Annotated[
        list[Document],
        Field(
            default_factory=list,
            description=(
                "All documents returned by the vector store for the generated queries. May include duplicates across "
                "queries before deduplication by chunk_id."
            ),
        ),
    ]
    filtered_docs: Annotated[
        list[Document],
        Field(
            default_factory=list,
            description=(
                "Subset of retrieved documents that the compress_docs node marked as relevant to the question. Only these "
                "documents are passed to the answer generation step."
            ),
        ),
    ]
    llm_answer: Annotated[
        LLMAnswer,
        Field(
            description=(
                "Structured answer produced by the generate_answer node. Contains the natural-language response, supporting "
                "quote, and the chunk_ids cited as evidence."
            ),
        ),
    ]
    llm_evidence_docs: Annotated[
        list[Document],
        Field(
            default_factory=list,
            description=(
                "Documents whose chunk_ids are referenced in llm_answer.chunk_ids. This set provides the full metadata and "
                "content for any cited evidence."
            ),
        ),
    ]
 



class OverallRetrievalState(InputRetrievalState, OutputRetrievalState):
    """"""
   