from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field

# NOTE: 
# LLM segment attributes are used as prompts via structured output 
# in LLM graph and OCR graph for metadata generation.

class BaseLLMSegmentAttributes(BaseModel):
    language: Annotated[
        Literal["de", "eng", "n/a"],
        Field(
            description="Detected document segment language; all outputs must use this language.",
        ),
    ]
    title: Annotated[
        str,
        Field(
            description=(
                "Original title of this document section, if present. "
                "If the section has no explicit title, create a short, precise, and informative title "
                "that clearly describes the content of this section."
            ),
        ),
    ]
    retrieval_summary: Annotated[
        str,
        Field(
            description=(
                "Write a short, retrieval-oriented summary of this document section in the same language as the original text."
                "Capture the main topic, important entities and concepts, their relationships, and any crucial numbers, dates, or identifiers. "
                "Use key domain terms and phrases that users might search for. 1-3 sentences, no bullet points."
            ),
        ),
    ]
    labels: Annotated[
        list[str],
        Field(
            default_factory=list,
            description=(
                "List of 2-3 short tags to enrich this section with metadata, "
            ),
        ),
    ]


# -------------------------------------------------------------------------------

class BaseSegmentAttributes(BaseModel):
    extracted_content: Annotated[
        str,
        Field(
            description=(
                "Note: The extracted content is generated by the OCR model in the OCR graph and by the LLM in the LLM graph."
                "The LLM can hallucinate content."
            ),
        ),
    ]
    metadata: Annotated[
        dict[str, Any],
        Field(
            default_factory=dict,
            description="",
        ),
    ]
    

# -------------------------------------------------------------------------------
class LLMException(BaseModel):
    page_number: Annotated[
        int,
        Field(
            default=None,
            description="PDF page number related to the exception, if known.",
        ),
    ]
    chunk_type: Annotated[
        str | None,
        Field(
            default=None,
            description="Chunk type being processed when the exception occurred.",
        ),
    ]
    chunk_index: Annotated[
        int | None,
        Field(
            default=None,
            description="Chunk index being processed when the exception occurred.",
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="Original exception message for debugging structured extraction failures.",
        ),
    ]
    traceback: Annotated[
        str | None,
        Field(
            default=None,
            description="Formatted traceback string when available.",
        ),
    ]
