@startuml
skinparam backgroundColor #FFFFFF  
skinparam shadowing false
skinparam arrowColor black
skinparam activityBackgroundColor lightgrey
skinparam activityBorderColor black

start


:Transfer State & Config;
    note left
        State:
        - pdf path

        Config:
        - doc_id
        - collection_id
        - extract_model
        - extract_data_prompt
        - embedding_model
    end note

partition "extract_metadata" {
   
:Load pdf metadata;
    note left
        PyMuPDF
        - fitz
    end note
:Add additional metadata;
    note left
        doc_id
        collection_id
        embedding_model
        extract_model
    end note
:Add doc metadata to state;
       
}


partition "llm_extract" {
   
:Load every pdf page as img -> list[PDFImage];
    note left
        pdf2image
    end note
:Genearte  text segments with llm for each pdf page img -> list[LLMSegment | Exception];

repeat 

:Map LLM-Response to segments;
    note left
        text_segments: list[TextSegment] 
        image_segments: list[ImageSegment]
        table_segments: list[TableOrListSegment] 
        code_or_formula_segments: list[CodeOrFormulaSegment] 
        other_segments: list[OtherSegment]
        llm_exceptions: list[LLMException] 
    end note

repeat while (Further LLM response?) is (Yes) not (No)

:Add segments to state;

}

partition "save" {
   
:Build vstore;
:Map segments to LangChain Doc -> list[Document];
:Filter complex metadata;
:Add docs to vstore;
:Add docs to state;
        
}


stop
@enduml